# docker-compose.yml
# Add this top-level entry
redis:
  image: redis
  container_name: redis
  expose:
    - 6379

polyottis:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 8081:8081
  links:
    - redis
  environment:
    - REDIS_URL=redis://redis
    - SMS_SERVICE_URL=http://35.184.27.27:8080/api/v1/sms
    - SECURITY_KEY=y7r39f86yg4hj0897fwhy988wg6